
# This is a basic workflow to help you get started with Actions

name: RollBack

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
      push:
            branches: production

env:
  AZURE_WEBAPP_NAME: githubactiondemo  # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: ${{ github.workspace }} # set this to the path to your web app project   
  GITHUB_REPOSITORY : ${{github.repository}}
  GITHUB_WORKSPACE : ${{ github.workspace }}
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_PUBLISH_PROFILE }}

jobs:
  build-deploy:
      
    name: Deploy
    
    runs-on: local_runner
    outputs:
      deploy-status: ${{ steps.set-status.outputs.status }}
#       output2: ${{ steps.step2.outputs.test }}
    steps:
    - uses: actions/checkout@master
    - name: Build with Maven
      id: build-step
      run: mvn package --file pom.xml
    - name : 'Deploy to Azure Webapp'
      id : deploy-step
      if: steps.build-step.outcome == 'success'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '${{env.GITHUB_WORKSPACE}}/target/*.war'
      continue-on-error: true
    - name : 'Set Status Failure' 
      id: set-status
      if: ${{steps.deploy-step.outcome == 'failure'}}
      run: echo "::set-output name=status::failure"
#     - name : 'Set Status Failure'
#       id: set-status
#       if: ${{steps.deploy-step.outcome == 'success'}}
#       run: echo "::set-output name=status::success"  
      
       
       
        
    
  rollback : 
        
        needs: [build-deploy]
        if : ${{needs.build-deploy.outputs.deploy-status == 'failure'}}
#         
#         if: ${{needs.build-deploy.result == 'failure'}}
        
        name : RollBack-Step
        runs-on: ubuntu-latest
        steps:
        - run : echo ${{needs.build-deploy.result}}    
        - name : Checkout production
          id: checkout-prod
          uses: actions/checkout@v2
          with:
                ref: 'production'
        - name: Build with Maven
          id: build-step
          run: mvn package --file pom.xml
        - name : 'Deploy to Azure Webapp'
          id : deploy-step
          uses: azure/webapps-deploy@v2
          with: 
              app-name: ${{ env.AZURE_WEBAPP_NAME }}
              publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
              package: '${{env.GITHUB_WORKSPACE}}/target/*.war'
    

#     - name : 'Check if steps have failed'
#       if : ${{ steps.build-step.outcome == 'success' }}
#       run: echo "In if block"
#     - name: 'Deploy to Azure WebApp'
#       uses: azure/webapps-deploy@v2
#       with: 
#         app-name: ${{ env.AZURE_WEBAPP_NAME }}
#         publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
#         package: './DemoProject.war'

